apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wbiyxh6kz-dotnet-basic
  janus-idp.io/tekton: wbiyxh6kz-dotnet-basic
  backstage.io/kubernetes-id: wbiyxh6kz-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wbiyxh6kz-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
